### ISSUE TITLE
No audio from speakers

### ISSUE THREAD

**Issue by Rich1975** [Gordon999/Pi_5B_LCD_MP3_Player#2]

**Comment by Rich1975** [comment]
Hi I am trying the 5 button player using raspberry pi 2w, a 20 column 4 line lcd display AND a innomaker raspberry pi audio hat (25 watt), the Raspberry Pi OS is Bullseye,.
I first set up the raspberry pi and Audio Hat as per Innomakers instructions, copied some audio files to the Music folder and using VLC i was able to hear the audio, next I hooked up the LCD and installed 5B_LCD_MP3_Player as per the instructions, now I dont hear audio. Any help/suggestions would be greatly appreciated. Attaching a few pics, hope this helps

![1](https://github.com/user-attachments/assets/a3afc298-7c12-43f1-b9b3-fc87aef85418)

![2](https://github.com/user-attachments/assets/1e4deecd-5ff9-4c9a-801a-b29c1d4c3003)

![IMG_20240714_183919864_HDR](https://github.com/user-attachments/assets/bc915867-2d90-40c4-9bad-fd415aa33430)

![IMG_20240714_185053823_HDR](https://github.com/user-attachments/assets/57c5fa80-f2d2-47f7-b45e-6b8f4aed15e2)

![IMG_20240714_185314099_HDR](https://github.com/user-attachments/assets/11c3a77e-e42d-453b-ae1c-954c4f4745f8)

![IMG_20240714_185530423_HDR](https://github.com/user-attachments/assets/e39bb594-09a0-4433-a4f1-03202306031f)

![IMG_20240714_191711989_HDR](https://github.com/user-attachments/assets/41fef364-75cc-4ac0-b2dd-ae39b1e7eb06)

**Comment by Rich1975** [comment]
HI, my concern is AO: [pulse] 44100HZ 2ch ....
does that mean that the Audio Output is sent to pulse???
With only the Hat software installed I get audio output, once I install 5B MP3 software there no more audio!

**Comment by Rich1975** [comment]
Hi,
 Seeing that your program works on its own with OR without a sound Hat/Bonnet BUT still get no sound from the speakers, I can only conclude there is something in your program inhibiting the sound production.
I have tried 
1 Innomaker Sound hat  -25 watts
2  A couple of Waveshare Audio hats (maybe 1 was defective)
and now
3 Adafruit i2s 3W Speaker Bonnet
Failed to work with ALL 3 products. Sorry!

**Comment by Gordon999** [comment]
Do you get sound out of your pi with other programs?

I simply use a standard pi installation and choose the audio output from the GUI, nothing complicated.

**Comment by Gordon999** [comment]
I have just built a new sd card with bullseye (legacy 32bit) and downloaded the script, and it needed a few updates, so v1.1
also 'sudo apt-get install python3-alsaaudio' was mssing from the instructions.
All worked fine using HDMI sound

what message do you get at startup ? eg ...

Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 39322 [60%] [on]
  Front Right: Playback 39322 [60%] [on]

**Comment by Rich1975** [comment]
Hi, using the Innomaker sound hat and your Pi-MP3_player cut down "0" I was able to complete a project, then using the same hardware I tried using Pi 5Button LCD MP3 Player and ended up with no sound. With the hookup as it is I then loaded VLC player and could hear the music, exit it and run the 5 button program and no sound, so, I bought the Waveshare audio hat, but, after multiple attempts with tech support I gave up and abandoned it and bought the Adafruit Speaker Bonnet which seems to work with VLC player, I would rather use the Innomaker Hat instead.
I will try the updated code and let you know the results

**Comment by Gordon999** [comment]
Does the innomaker hat appear in the list 
![IMG_20240913_200829](https://github.com/user-attachments/assets/877d8e3e-67a5-40a3-8880-a2c183d1642f)

**Comment by Gordon999** [comment]
I wonder if there's a clash here....this is your amp connections to i2c
![IMG_20240913_210544](https://github.com/user-attachments/assets/4089cc6a-1353-41b0-876b-a66b2d8285a6)

**Comment by Rich1975** [comment]
On July 14th I commented about this problem and sent some pictures, 1) was of i2c detect results and 2) Alsa mixer, if anything has changed in version 1.1 I haven't yet tried it . At that time I had already installed alsaaudio as per your updated notes. will keep you updated if you don't mind.
 Thank you

**Comment by Gordon999** [comment]
Not sure l can resolve this. It appears to be an issue between the lcd screen and audio amplifier not the python script.

**Comment by Gordon999** [comment]
Regards your 5 button issue try 5B_LCD_MP3_Player2.py, as the backlight in the original version maybe stopped the 25W amp audio. Disconnect any wire you had on pin40, and put the link back on the lcd pcb, if you ever removed it !

If there are issues with the backlight not working try 5B_LCD_MP3_Player.py v1.3 where the backlight has moved to pin 38

I don't have the innomaker 25w amp but now have the innomaker dac hat which uses the same pi pins for input and it works fine with the latest code.

**Comment by Gordon999** [comment]
Assumed resolved...

**Comment by Gordon999** [comment]
I have bought and fitted an innomaker 25W amp hat and it works fine with this code.

I added dtoverlay=hifiberry-amp to /boot/firmware/config.txt

using pi4, bookworm 64bit full version, 12v psu

**Comment by Gordon999** [comment]
Now tried a Pi3B and a Pi Zero 2w with the innomaker 25w amp  and all works fine

**Comment by Gordon999** [comment]
I made use of the amp and made a player with built in speakers...
![20241128_103337](https://github.com/user-attachments/assets/f0050558-f3b3-4c50-9f4e-22e4662fae4f)
![20241128_103543](https://github.com/user-attachments/assets/8f61ca91-4fca-4add-8ce0-923eff8c0e71)
![20241128_103606](https://github.com/user-attachments/assets/4c325c3b-a9e8-4477-87cf-e1c531b4554d)
